# Copyright (c) Facebook, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: 2.1

jobs:
  # the same recipe doesn't work for Debian 10 yet.
  py37_ubuntu1804:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python3 python3-dev python3-pip python3-venv # python 3.6.9

            # packages for headless rendering
            apt-get install -y libgl1-mesa-glx libosmesa6 freeglut3 freeglut3-dev

      - run:
          name: Install TACTO package, required dependencies, and run unit tests
          command: |
            pip3 install nox
            PYOPENGL_PLATFORM=osmesa nox

workflows:
  version: 2
  build:
    jobs:
      - py37_ubuntu1804
