# Copyright (c) Facebook, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: 2.1

jobs:
  # the same recipe doesn't work for Debian 10 yet.
  py37_ubuntu1804:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python3 python3-dev python3-pip python3-venv # python 3.6.9

            # For headless rendering
            apt-get install -y libgl1-mesa-glx libosmesa6 freeglut3 freeglut3-dev

            pip3 install -U pip

      - run:
          name: Install pip dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements-examples.txt
            python3 setup.py install

      - run:
          name: Test TACTO Simulator
          command: |
            . venv/bin/activate
            # Need a specific version of PyOpenGL (forked & modified by mmatl)
            # for pyrender to work headlessly using OSMesa
            # pip3 install -U pip
            pip3 install git+https://github.com/mmatl/pyopengl.git@76d1261adee2d3fd99b418e75b0416bb7d2865e6

            pip3 install .
            pip3 install pytest
            PYOPENGL_PLATFORM=osmesa pytest

workflows:
  version: 2
  build:
    jobs:
      - py37_ubuntu1804
